### ISSUE TITLE
OpenFile crashes on OSX

### ISSUE THREAD

**Issue by raulvera59** [andlabs/ui#107]
The following is a small program to capture a filename using ui.OpenFile:
```go
package main

import (
	"github.com/andlabs/ui"
)

var window ui.Window
var srcName string

func loadFile(filename string) {
	srcName = filename
}

func initUI() {
	b := ui.NewButton("Read")
	b.OnClicked(func() {
		ui.OpenFile (window, loadFile)
	})
	window = ui.NewWindow("Window", 200, 200, b)
        window.OnClosing(func() bool {
        ui.Stop()
        return true
    })
    window.Show()
}

func main() {
    go ui.Do(initUI)
    err := ui.Go()
    if err != nil {
        panic(err)
    }
}
```
When I run it on OSX, it crashes with the following stack trace (I don't have an available Windows or Unix box to check those):
```
$ sippui
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x2d pc=0x4041f43]

goroutine 1 [running, locked to thread]:
github.com/andlabs/ui.finishOpenFile(0x4358b30, 0xc20801d5a0)
	/Users/Raul/gocode/src/github.com/andlabs/ui/dialog_darwin.go:24 +0xa3
github.com/andlabs/ui._Cfunc_uimsgloop()
	/Users/Raul/gocode/src/github.com/andlabs/ui/:442 +0x45
github.com/andlabs/ui.uimsgloop()
	/Users/Raul/gocode/src/github.com/andlabs/ui/uitask_darwin.go:27 +0x1b
github.com/andlabs/ui.Go(0x0, 0x0)
	/Users/Raul/gocode/src/github.com/andlabs/ui/uitask.go:22 +0x74
main.main()
	/Users/Raul/gocode/src/github.com/Causticity/sipp/sippui/main.go:29 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [chan receive]:
github.com/andlabs/ui.uiissueloop()
	/Users/Raul/gocode/src/github.com/andlabs/ui/uitask.go:59 +0x53
created by github.com/andlabs/ui.Go
	/Users/Raul/gocode/src/github.com/andlabs/ui/uitask.go:21 +0x6d
$ 
```
To me it looks like OpenFile has a bug causing it to crash on invocation of the callback, but perhaps I'm missing something.

**Comment by andlabs** [comment]
Probably; I'm not sure. libui has a new OpenFile interface that doesn't take a callback, so we'll see what happens then...

**Comment by doamatto** [comment]
Not to necro, but rather bump this issue as I'm running into it as well:
```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4800d2]

goroutine 1 [running, locked to thread]:
github.com/andlabs/ui.OpenFile.func1(0x0, 0xc0000b4000)
        /home/doamatto/go/pkg/mod/github.com/andlabs/ui@v0.0.0-20200610043537-70a69d6ae31e/stddialogs.go:18 +0x22
github.com/andlabs/ui.OpenFile(0x0, 0x0, 0x0)
        /home/doamatto/go/pkg/mod/github.com/andlabs/ui@v0.0.0-20200610043537-70a69d6ae31e/stddialogs.go:18 +0x44
main.main.func1.1(0xc00009c270)
        /home/doamatto/[...]/main.go:37 +0x36
github.com/andlabs/ui.pkguiDoButtonOnClicked(0x1d60e10, 0x0)
        /home/doamatto/go/pkg/mod/github.com/andlabs/ui@v0.0.0-20200610043537-70a69d6ae31e/button.go:60 +0x7b
github.com/andlabs/ui._cgoexpwrap_e99bb8362bf9_pkguiDoButtonOnClicked(0x1d60e10, 0x0)
        _cgo_gotypes.go:3863 +0x35
github.com/andlabs/ui._Cfunc_uiMain()
        _cgo_gotypes.go:2519 +0x41
github.com/andlabs/ui.Main(0x4cc5f0, 0x0, 0xc00008e058)
        /home/doamatto/go/pkg/mod/github.com/andlabs/ui@v0.0.0-20200610043537-70a69d6ae31e/main.go:41 +0xff
main.main()
        /home/doamatto/[...]/main.go:11 +0x2d
```
