### ISSUE TITLE
has it considered golang 1.6?

### ISSUE THREAD

**Issue by qiukeren** [andlabs/ui#118]
when using the old version of andlabs/ui with golang1.6,
it may panic with `panic: runtime error: cgo argument has Go pointer to Go pointer`

what about the new version?

now golang 1.6 has have the new rules of pointer when using cgo between ang go. http://blog.golang.org/go1.6

```
Users of cgo should be aware of major changes to the rules for sharing pointers between Go and C code. The rules are designed to ensure that such C code can coexist with Go's garbage collector and are checked during program execution, so code may require changes to avoid crashes. See the release notes and cgo documentation for the details.
```

**Comment by andlabs** [comment]
I'm already not giving Go pointers to the C side; maybe I forgot something? Please print the full panic backtrace. I'll have to see what I'm doing wrong...

**Comment by qiukeren** [comment]
it's not an emergency issue for the old version ,but a notification for the new version.

git commit at
```
commit de9d72299fb89a8b6cdc8963cd6b6ae708a81e80
Author: Pietro Gagliardi <pietro10@mac.com>
Date:   Thu Apr 16 16:38:33 2015 -0400

    Cleaned up unix/button.c a bit.
```

example basicwindow panic:
```
mudu ~/gopath/src/github.com/andlabs/ui/examples/basicwindow $ ./basicwindow 
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 4 [running]:
panic(0x410b360, 0xc82000a110)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/andlabs/ui._cgoCheckPointer0(0x40defe0, 0xc820072098, 0x0, 0x0, 0x0, 0xc8200277a8)
	??:0 +0x4d
github.com/andlabs/ui.issue(0xc820072098)
	/Users/mudu/gopath/src/github.com/andlabs/ui/uitask_darwin.go:35 +0x48
github.com/andlabs/ui.uiissueloop()
	/Users/mudu/gopath/src/github.com/andlabs/ui/uitask.go:60 +0x66
created by github.com/andlabs/ui.Go
	/Users/mudu/gopath/src/github.com/andlabs/ui/uitask.go:21 +0xd2
```

example widgetgallery panic:
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 18 [running]:
panic(0x4142a00, 0xc820092000)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/andlabs/ui._cgoCheckPointer0(0x410aae0, 0xc82002a098, 0x0, 0x0, 0x0, 0xc8200227a8)
	??:0 +0x4d
github.com/andlabs/ui.issue(0xc82002a098)
	/Users/mudu/gopath/src/github.com/andlabs/ui/uitask_darwin.go:35 +0x48
github.com/andlabs/ui.uiissueloop()
	/Users/mudu/gopath/src/github.com/andlabs/ui/uitask.go:60 +0x66
created by github.com/andlabs/ui.Go
	/Users/mudu/gopath/src/github.com/andlabs/ui/uitask.go:21 +0xd2
```

**Comment by andlabs** [comment]
Oh yes, that's the previous package ui code. Part of the reason for my rewrite was this exact scenario happening. Unfortunately, that codebase is now discontinued; you can try fixing it manually but it'll be a lot of work as you have to make sure no Go pointer touches C. The new package ui is stable enough (but not yet feature complete). Sorry.

**Comment by qiukeren** [comment]
Well, I close this topic at this time 👍 

Tested on mac(sierra) with go 1.7.3, windows 7 32bit with go 1.7.3 +mingw-x64

this library is stable.
