### ISSUE TITLE
Wiki example crash on enter key

### ISSUE THREAD

**Issue by jfcg** [andlabs/ui#131]
I downloaded/built ui & libui master yesterday on Windows 7 64-bit. Then I built the example from [the wiki](https://github.com/andlabs/ui/wiki/Getting-Started). It works fine until I press "enter" key which gives the following crash
```
Exception 0x80000003 0x0 0x0 0x7fefd3c31f2
PC=0x7fefd3c31f2
signal arrived during external code execution
github.com/andlabs/ui._Cfunc_uiMain()
??:0 +0x3d
github.com/andlabs/ui.start(0xc08200e1e0, 0x4c4600)
D:/Serhat/Go/src/github.com/andlabs/ui/main.go:56 +0x208
created by github.com/andlabs/ui.Main
D:/Serhat/Go/src/github.com/andlabs/ui/main.go:36 +0x74
goroutine 1 [chan receive]:
github.com/andlabs/ui.Main(0x4c4600, 0x0, 0x0)
D:/Serhat/Go/src/github.com/andlabs/ui/main.go:37 +0xa4
main.main()
D:/Serhat/Go/src/ui/ui-sample.go:8 +0x2a
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
d:/go/src/runtime/asm_amd64.s:1998 +0x1
rax 0x30
rbx 0x111
rcx 0x28
rdi 0x22f960
rsi 0x1
rbp 0x4d05d0
rsp 0x22f8f8
r8 0x7fee4b193a8
r9 0x2ead10
r10 0x42
r11 0x24007a0023
r12 0x0
r13 0x111
r14 0x2a5f48
r15 0x4d05d0
rip 0x7fefd3c31f2
rflags 0x206
cs 0x33
fs 0x53
gs 0x2b
```

**Comment by andlabs** [comment]
This is a bug that has to do with legacy stuff dating back to Windows 1.0. There's a TODO about it somewhere in the source; more details [here](http://blogs.msdn.com/b/oldnewthing/archive/2007/08/20/4470527.aspx). I have to figure out how to fix it.

**Comment by andlabs** [comment]
Migrated to [libui#55](https://github.com/andlabs/libui/issues/55).
