### ISSUE TITLE
Could you help me get process name by pid in windows ?

### ISSUE THREAD

**Issue by tinycedar** [andlabs/ui#161]
I'd like to get process name by pid in windows by Go, and seems QueryFullProcessImageNameA called successfully but find that error occurs on print process name, could you please help me figure it out ? I do really appreciate your help.
```
func openProcess(pid uint32) string {
	procOpenProcess := syscall.NewLazyDLL("Kernel32.dll").NewProc("OpenProcess")
	var dwDesiredAccess uint32 = 0x0400 | 0x0010
	openPid, _, _ := procOpenProcess.Call(uintptr(unsafe.Pointer(&dwDesiredAccess)), 0, uintptr(pid))
	if openPid > 0 {
		procQueryFullProcessImageName := syscall.NewLazyDLL("Kernel32.dll").NewProc("QueryFullProcessImageNameA")
		var processName = make([]int8, 102400)
		var cbNeeded uint32 = 102400
		fmt.Println(procQueryFullProcessImageName.Call(uintptr(openPid), 0, uintptr(unsafe.Pointer(&processName)), uintptr(unsafe.Pointer(&cbNeeded))))
		fmt.Println(processName)
	} else {
		fmt.Println("Error calling OpenProcess:  ", pid)
	}
	return ""
}
```

Ouptput:
```
go run getProcess.go
2016/06/26 23:18:42 time elapsed: 2.4999ms
1 0 The operation completed successfully.
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x456f91]
goroutine 1 [running]:
runtime.throw(0x518370, 0x5)
        C:/go/src/runtime/panic.go:530 +0x97 fp=0xc082028fb8 sp=0xc082028fa0
runtime.sigpanic()
        C:/go/src/runtime/signal_windows.go:164 +0x12a fp=0xc082028fe0 sp=0xc082028fb8
runtime.memmove(0xc08200677f, 0x72676f72505c3a43, 0x1)
        C:/go/src/runtime/memmove_amd64.s:122 +0x1f1 fp=0xc082028fe8 sp=0xc082028fe0
runtime.typedmemmove(0x4cfc80, 0xc08200677f, 0x72676f72505c3a43)
        C:/go/src/runtime/mbarrier.go:190 +0x29 fp=0xc082029018 sp=0xc082028fe8
reflect.typedmemmove(0x4cfc80, 0xc08200677f, 0x72676f72505c3a43)
        C:/go/src/runtime/mbarrier.go:202 +0x3c fp=0xc082029038 sp=0xc082029018
reflect.packEface(0x4cfc80, 0x72676f72505c3a43, 0x183, 0x0, 0x0)
        C:/go/src/reflect/value.go:113 +0x127 fp=0xc0820290a8 sp=0xc082029038
reflect.valueInterface(0x4cfc80, 0x72676f72505c3a43, 0x183, 0x1, 0x0, 0x0)
        C:/go/src/reflect/value.go:938 +0x1f3 fp=0xc082029100 sp=0xc0820290a8
reflect.Value.Interface(0x4cfc80, 0x72676f72505c3a43, 0x183, 0x0, 0x0)
        C:/go/src/reflect/value.go:908 +0x4f fp=0xc082029138 sp=0xc082029100
fmt.(*pp).printValue(0xc08202c1a0, 0x4cfc80, 0x72676f72505c3a43, 0x183, 0x76, 0x1, 0x183)
        C:/go/src/fmt/print.go:842 +0x379 fp=0xc082029228 sp=0xc082029138
fmt.(*pp).printReflectValue(0xc08202c1a0, 0x4cabe0, 0xc082003ea0, 0x97, 0x76, 0x0, 0x0)
        C:/go/src/fmt/print.go:990 +0x13ea fp=0xc0820299e0 sp=0xc082029228
fmt.(*pp).printArg(0xc08202c1a0, 0x4cabe0, 0xc082003ea0, 0x76, 0x0, 0x0)
        C:/go/src/fmt/print.go:810 +0x547 fp=0xc082029b68 sp=0xc0820299e0
fmt.(*pp).doPrint(0xc08202c1a0, 0xc082029e18, 0x1, 0x1, 0x101)
        C:/go/src/fmt/print.go:1273 +0x254 fp=0xc082029c68 sp=0xc082029b68
fmt.Fprintln(0x7541c0, 0xc08201e010, 0xc082029e18, 0x1, 0x1, 0x40d175, 0x0, 0x0)
        C:/go/src/fmt/print.go:254 +0x6e fp=0xc082029cb0 sp=0xc082029c68
fmt.Println(0xc082029e18, 0x1, 0x1, 0x4cabe0, 0x0, 0x0)
        C:/go/src/fmt/print.go:264 +0x7a fp=0xc082029d08 sp=0xc082029cb0
main.openProcess(0xc0000012d0, 0x0, 0x0)                                                                    d:/go/src/github.com/tinycedar/lily/getProcess.go:49 +0x69a fp=0xc082029ed0 sp=0xc082029d08
main.main()
        d:/go/src/github.com/tinycedar/lily/getProcess.go:18 +0x86 fp=0xc082029f40 sp=0xc082029ed0
runtime.main()
        C:/go/src/runtime/proc.go:188 +0x27e fp=0xc082029f90 sp=0xc082029f40
runtime.goexit()
        C:/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082029f98 sp=0xc082029f90
exit status 2
```

**Comment by andlabs** [comment]
This is the same slice issue as last time. Fortunately the fix is easy: pass `&processName[0]` instead of `&processName`.

**Comment by tinycedar** [comment]
Thanks a lot once again !
