### ISSUE TITLE
gtk backend ramdomly crash

### ISSUE THREAD

**Issue by F0rth** [andlabs/ui#167]
Here is my ui.go test program:
```
package main

import (
	"github.com/andlabs/ui"
	"time"
	"strconv"
        "math"
)

var c = make(chan int)

func main() {

	err := ui.Main(func() {
		d := 0
		debug := ui.NewLabel("test program")
		count := ui.NewLabel("countdown: ")
		button := ui.NewButton("launch")
		quitter := ui.NewButton("Quit")
		days := ui.NewLabel(strconv.Itoa(d))
		bar := ui.NewProgressBar()
		box := ui.NewVerticalBox()
		box.Append(count, false)
		box.Append(button, false)
		box.Append(days, false)
		box.Append(bar, false)
		box.Append(quitter, false)
		box.Append(debug, false)
		bar.SetValue(d)
		window := ui.NewWindow("Test", 200, 200, false)
		window.SetChild(box)
		button.OnClicked(func(*ui.Button) {
			go incr()
		})
		quitter.OnClicked(func(*ui.Button) {
			ui.Quit()
			})
		window.OnClosing(func(*ui.Window) bool {
			ui.Quit()
			return true
		})
		window.Show()
		go func() {
			for {
				d := <-c
				bar.SetValue(int(math.Floor(100 * float64(float64(d)/float64(1000)))))
				bar.Show()
				days.SetText(strconv.Itoa(1000 - d))
				days.Show()
			}
		}()
	})

	if err != nil {
		panic(err)
	}

}

func incr() {
	var i int
	for ; i <= 1000; i++ {
		c <- i
		time.Sleep(10 * time.Millisecond)
	}
}
```

and the crash messages:
```
(ui:11119): Gtk-WARNING **: Allocating size to GtkWindow 0x2ac62c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(ui:11119): Gtk-WARNING **: Allocating size to GtkLabel 0x2831950 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(ui:11119): Pango-CRITICAL **: pango_cairo_show_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed

(ui:11119): Gtk-WARNING **: Allocating size to GtkWindow 0x2ac62c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(ui:11119): Gtk-WARNING **: Allocating size to GtkBox 0x286d3c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(ui:11119): Pango-CRITICAL **: pango_layout_get_line_count: assertion 'layout != NULL' failed

(ui:11119): Gtk-CRITICAL **: gtk_render_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed
[forth@mjolnir]$ ./ui

(ui:11134): Pango-CRITICAL **: pango_layout_get_line_count: assertion 'layout != NULL' failed

(ui:11134): Gtk-CRITICAL **: gtk_render_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed

(ui:11134): Pango-CRITICAL **: pango_layout_get_line_count: assertion 'layout != NULL' failed

(ui:11134): Gtk-CRITICAL **: gtk_render_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed
[forth@mjolnir]$ ./ui

(ui:11153): Gtk-WARNING **: Allocating size to GtkWindow 0x11922c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(ui:11153): Gtk-WARNING **: Allocating size to GtkBox 0xf393c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(ui:11153): Pango-CRITICAL **: pango_layout_set_attributes: assertion 'layout != NULL' failed

(ui:11153): Pango-CRITICAL **: pango_layout_set_alignment: assertion 'layout != NULL' failed

(ui:11153): Pango-CRITICAL **: pango_layout_set_ellipsize: assertion 'PANGO_IS_LAYOUT (layout)' failed

(ui:11153): Pango-CRITICAL **: pango_layout_set_wrap: assertion 'PANGO_IS_LAYOUT (layout)' failed

(ui:11153): Pango-CRITICAL **: pango_layout_set_single_paragraph_mode: assertion 'PANGO_IS_LAYOUT (layout)' failed
**
Gtk:ERROR:gtklabel.c:3390:gtk_label_update_layout_width: assertion failed: (priv->layout)
SIGABRT: abort
PC=0x7fbcfade4295 m=0
signal arrived during cgo execution

goroutine 5 [syscall, locked to thread]:
runtime.cgocall(0x687960, 0xc82003bf20, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82003bef8 sp=0xc82003bec8
github.com/andlabs/ui._Cfunc_uiMain()
	??:0 +0x36 fp=0xc82003bf20 sp=0xc82003bef8
github.com/andlabs/ui.start(0xc8200142a0, 0x84a638)
	/home/forth/go/src/github.com/andlabs/ui/main.go:56 +0x1f3 fp=0xc82003bfa0 sp=0xc82003bf20
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003bfa8 sp=0xc82003bfa0
created by github.com/andlabs/ui.Main
	/home/forth/go/src/github.com/andlabs/ui/main.go:36 +0x6d

goroutine 1 [chan receive]:
github.com/andlabs/ui.Main(0x84a638, 0x0, 0x0)
	/home/forth/go/src/github.com/andlabs/ui/main.go:37 +0x9d
main.main()
	/home/forth/ui.go:17 +0x23

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [chan receive]:
main.main.func1.4(0xc82000af30, 0xc82000af20)
	/home/forth/ui.go:48 +0x46
created by main.main.func1
	/home/forth/ui.go:54 +0x43d

goroutine 7 [sleep]:
time.Sleep(0x989680)
	/usr/lib/go/src/runtime/time.go:59 +0xf9
main.incr()
	/home/forth/ui.go:67 +0x5a
created by main.main.func1.1
	/home/forth/ui.go:36 +0x2b

rax    0x0
rbx    0x101bf10
rcx    0x7fbcfade4295
rdx    0x6
rdi    0x2b91
rsi    0x2b91
rbp    0x5a
rsp    0x7ffcb13db3c8
r8     0x101bf10
r9     0x0
r10    0x8
r11    0x202
r12    0x7fbcfb67d2e0
r13    0x7fbcfd0fc890
r14    0x7ffcb13db500
r15    0xefd7f0
rip    0x7fbcfade4295
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by andlabs** [comment]
```
        go func() {
            for {
                d := <-c
                bar.SetValue(int(math.Floor(100 * float64(float64(d)/float64(1000)))))
                bar.Show()
                days.SetText(strconv.Itoa(1000 - d))
                days.Show()
            }
        }()
```

You can't call methods on `bar` or `days` from another goroutine. You'll need to wrap those in a `ui.QueueMain()`.

**Comment by F0rth** [comment]
Thanks.
