### ISSUE TITLE
EXCEPTION,BUT I UNKOWN IT

### ISSUE THREAD

**Issue by maosjz** [andlabs/ui#335]
Exception 0xc0000005 0x0 0xffffffffffffffff 0xa49033
PC=0xa49033

runtime: unknown pc 0xa49033
stack: frame={sp:0x99cfb58, fp:0x0} stack=[0x97d1ed0,0x99cfed0)
00000000099cfa58:  00000000099cfac0  00000000099cfaa0 
00000000099cfa68:  00000000099cfc63  00000000099cfaa0 
00000000099cfa78:  00000000009ade4c  00000000099cfb10 
00000000099cfa88:  00000000009a6a23  00000000002dc000 
00000000099cfa98:  00000000099cfac0  0000000000000000 
00000000099cfaa8:  00000000099cfcbf  00000000099cfae0 
00000000099cfab8:  00000000009aa025  00000000002d9e40 
00000000099cfac8:  0000000000000030  00000000099cfb00 
00000000099cfad8:  00000000099cfcbf  00000000099cfb10 
00000000099cfae8:  00000000009ade1c  00000000002d9e40 
00000000099cfaf8:  0000000000a0e4d2  0000000000b90700 
00000000099cfb08:  00000000002dc000  00000000099cfb40 
00000000099cfb18:  0000000000a37595  00000000002d9e20 
00000000099cfb28:  00000000099cfb50  00000000099cfb60 
00000000099cfb38:  00000000009aa025  00000000099cfb80 
00000000099cfb48:  0000000000a37494  00000000099cfb7f 
00000000099cfb58: <0000000000a0f16b  00000000099cfb90 
00000000099cfb68:  00000000009ade1c  00000000002dc000 
00000000099cfb78:  00000000002d9e20  00000000099cfbf0 
00000000099cfb88:  0000000000a37106  00000000099cfbb8 
00000000099cfb98:  00000000002d9270  00000000002d98e0 
00000000099cfba8:  0000000000a369af  0000000000b90700 
00000000099cfbb8:  00000000002d9e20  00000000002d9e20 
00000000099cfbc8:  0000000000a37464  00000000099cfbff 
00000000099cfbd8:  00000000002dc000  00000000002d9e40 
00000000099cfbe8:  00000000002dbfe0  00000000099cfcc0 
00000000099cfbf8:  00000000099cfcbf  00000000099cfc50 
00000000099cfc08:  0000000000a36d83  00000000099cfc30 
00000000099cfc18:  0000000000b90700  00000000002d9e20 
00000000099cfc28:  00000000002dc000  00000000099cfc60 
00000000099cfc38:  0000000000a16410  00000000099cfcc0 
00000000099cfc48:  00000000002dbfe0  0000000000b90700 
runtime: unknown pc 0xa49033
stack: frame={sp:0x99cfb58, fp:0x0} stack=[0x97d1ed0,0x99cfed0)
00000000099cfa58:  00000000099cfac0  00000000099cfaa0 
00000000099cfa68:  00000000099cfc63  00000000099cfaa0 
00000000099cfa78:  00000000009ade4c  00000000099cfb10 
00000000099cfa88:  00000000009a6a23  00000000002dc000 
00000000099cfa98:  00000000099cfac0  0000000000000000 
00000000099cfaa8:  00000000099cfcbf  00000000099cfae0 
00000000099cfab8:  00000000009aa025  00000000002d9e40 
00000000099cfac8:  0000000000000030  00000000099cfb00 
00000000099cfad8:  00000000099cfcbf  00000000099cfb10 
00000000099cfae8:  00000000009ade1c  00000000002d9e40 
00000000099cfaf8:  0000000000a0e4d2  0000000000b90700 
00000000099cfb08:  00000000002dc000  00000000099cfb40 
00000000099cfb18:  0000000000a37595  00000000002d9e20 
00000000099cfb28:  00000000099cfb50  00000000099cfb60 
00000000099cfb38:  00000000009aa025  00000000099cfb80 
00000000099cfb48:  0000000000a37494  00000000099cfb7f 
00000000099cfb58: <0000000000a0f16b  00000000099cfb90 
00000000099cfb68:  00000000009ade1c  00000000002dc000 
00000000099cfb78:  00000000002d9e20  00000000099cfbf0 
00000000099cfb88:  0000000000a37106  00000000099cfbb8 
00000000099cfb98:  00000000002d9270  00000000002d98e0 
00000000099cfba8:  0000000000a369af  0000000000b90700 
00000000099cfbb8:  00000000002d9e20  00000000002d9e20 
00000000099cfbc8:  0000000000a37464  00000000099cfbff 
00000000099cfbd8:  00000000002dc000  00000000002d9e40 
00000000099cfbe8:  00000000002dbfe0  00000000099cfcc0 
00000000099cfbf8:  00000000099cfcbf  00000000099cfc50 
00000000099cfc08:  0000000000a36d83  00000000099cfc30 
00000000099cfc18:  0000000000b90700  00000000002d9e20 
00000000099cfc28:  00000000002dc000  00000000099cfc60 
00000000099cfc38:  0000000000a16410  00000000099cfcc0 
00000000099cfc48:  00000000002dbfe0  0000000000b90700 

goroutine 491 [syscall]:
github.com/andlabs/ui._Cfunc_uiMultilineEntryAppend(0x2d7610, 0x2d88f0)
	_cgo_gotypes.go:2555 +0x4c
github.com/andlabs/ui.(*MultilineEntry).Append.func1(0x2d7610, 0x2d88f0)
	C:/Users/pc/go/src/github.com/andlabs/ui/multilineentry.go:68 +0x6c
github.com/andlabs/ui.(*MultilineEntry).Append(0xc042072ff0, 0xc042fabf38, 0x17)
	C:/Users/pc/go/src/github.com/andlabs/ui/multilineentry.go:68 +0x64

**Comment by maosjz** [comment]
for i:=1;i<=s;i++  {
			go func(i int) {
				start := time.Now()
				_,err := fetcher.Fetch(url)
				if(err != nil) {
					println("error")
				} else {
					cost := time.Since(start)
					mutilineEntry.Append("THREAD:"+strconv.Itoa(i)+":"+cost.String()+"\n")
				}

			}(i)
		}

**Comment by andlabs** [comment]
You can't call `multilineEntry.Append` directly from a goroutine; you must wrap that in `ui.QueueMain`.

**Comment by andlabs** [comment]
Any update?
