### ISSUE TITLE
Exception when running tests

### ISSUE THREAD

**Issue by bbigras-** [andlabs/ui#59]
go version go1.4rc1 windows/amd64

1. run `go test`
- Select the `Foreign Events` tab
- Click the `Open` button
- Close the file dialog

As soon as I close the file dialog I get this exception :

```
d:\Dev\go\gopath\src\github.com\andlabs\ui>go test
Exception 0xc0000005 0x8 0xc328c48348 0xc328c48348
PC=0xc328c48348


goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/andlabs/ui.func┬À024()
        d:/dev/go/gopath/src/github.com/andlabs/ui/zz_test.go:310 +0x10d
created by github.com/andlabs/ui.init┬À1
        d:/dev/go/gopath/src/github.com/andlabs/ui/zz_test.go:311 +0x35

goroutine 6 [chan receive]:
github.com/andlabs/ui.uiissueloop()
        d:/dev/go/gopath/src/github.com/andlabs/ui/uitask.go:59 +0x5a
created by github.com/andlabs/ui.Go
        d:/dev/go/gopath/src/github.com/andlabs/ui/uitask.go:21 +0x74
rax     0x43b110
rbx     0xc328c48348
rcx     0x0
rdx     0x461f40
rdi     0xc082071dd8
rsi     0x22fc30
rbp     0x0
rsp     0xc082071d88
r8      0xc082071df0
r9      0x6ecda0
r10     0x0
r11     0x246
r12     0x0
r13     0x800d
r14     0x0
r15     0xb065a
rip     0xc328c48348
rflags  0xc300010246
cs      0x33
fs      0x53
gs      0x2b
exit status 2
FAIL    github.com/andlabs/ui   23.362s
```

**Comment by andlabs** [comment]
No longer relevant to the current version of package ui.
